### ISSUE TITLE
.gitexternals parsing

### ISSUE THREAD

**Issue by halfflat** [Eyescale/CMake#271]
It looks like the GitExternals script both includes (line 148) the .gitexternals file and also scans it for directory-repository-tag information. However the scanning script will throw a fatal error if there exists a non-comment line in the file (line 153). Doesn't this make the include redundant?

**Comment by eile** [comment]
The include is there so that a cmake rerun is triggered when you change the file. The more intuitive way is how it's done for .gitsubprojects, but this I understood to late.

https://github.com/Eyescale/Collage/blob/master/.gitsubprojects
https://github.com/Eyescale/CMake/blob/master/SubProject.cmake

**Comment by halfflat** [comment]
Thanks for the explanation!
